2024-08-23 12:51:56,376 INFO: Event tracked successfully: productId=1, eventType=view [in /home/runner/Naurish/app/main/routes.py:643]
2024-08-23 12:55:30,229 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 12:55:47,514 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 12:56:00,291 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 12:56:18,230 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 12:56:37,088 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 12:58:36,227 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 12:58:38,409 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 13:05:25,761 INFO: User logged out: bha. Total logged in users: 0 [in /home/runner/Naurish/app/__init__.py:63]
2024-08-23 13:05:25,761 INFO: User logged out: bha [in /home/runner/Naurish/app/auth/routes.py:170]
2024-08-23 13:05:40,945 INFO: User logged in: bha. Total logged in users: 1 [in /home/runner/Naurish/app/__init__.py:57]
2024-08-23 13:05:41,032 INFO: User logged in: bha, IP: 172.31.196.76 [in /home/runner/Naurish/app/auth/routes.py:136]
2024-08-23 13:09:17,756 INFO: User logged out: bha. Total logged in users: 0 [in /home/runner/Naurish/app/__init__.py:63]
2024-08-23 13:09:17,758 INFO: User logged out: bha [in /home/runner/Naurish/app/auth/routes.py:170]
2024-08-23 13:13:32,636 INFO: User logged in: bha. Total logged in users: 1 [in /home/runner/Naurish/app/__init__.py:57]
2024-08-23 13:13:32,714 INFO: User logged in: bha, IP: 172.31.196.76 [in /home/runner/Naurish/app/auth/routes.py:136]
2024-08-23 13:14:41,835 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:41,856 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:41,874 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:42,266 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:57,579 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:57,589 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:57,613 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:14:57,763 ERROR: Error tracking event: name 'SQLAlchemyError' is not defined [in /home/runner/Naurish/app/main/routes.py:646]
Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 679, in record_view_event
    new_view = ProductView(
NameError: name 'ProductView' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Naurish/app/main/routes.py", line 638, in track_event
    record_view_event(user_id, guest_ip, product_id, parsed_timestamp)
  File "/home/runner/Naurish/app/main/routes.py", line 696, in record_view_event
    except SQLAlchemyError as e:
NameError: name 'SQLAlchemyError' is not defined
2024-08-23 13:51:34,737 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 13:51:38,041 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:10:33,514 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:10:38,245 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:10:43,058 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:11:38,189 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:11:57,218 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:12:24,773 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:12:38,858 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:12:44,624 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:12:49,441 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:12:59,503 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:43:32,661 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:43:42,490 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:44:55,092 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:44:59,702 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:45:42,477 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:47:00,133 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:47:22,668 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
2024-08-23 14:47:33,218 INFO: Nourisha Grocery Store application started [in /home/runner/Naurish/app/__init__.py:109]
